# Generated by Django 4.2.24 on 2025-09-05 16:39

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrderModel",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("user_id", models.UUIDField()),
                ("status", models.CharField(default="pending", max_length=20)),
                ("total_price", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("final_price", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "db_table": "order",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user_id"], name="order_user_id_60f97d_idx"),
                    models.Index(fields=["status"], name="order_status_35c31c_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="OrderItemModel",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("product_id", models.UUIDField()),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="items", to="orders.ordermodel"
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Item",
                "verbose_name_plural": "Order Items",
                "db_table": "order_item",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(fields=["order"], name="order_item_order_i_08a5da_idx"),
                    models.Index(fields=["product_id"], name="order_item_product_442025_idx"),
                ],
            },
        ),
    ]
