services:
  db:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5500:${POSTGRES_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.2.0
    container_name: grocery_redis
    env_file:
      - .env
    ports:
      - "6400:${REDIS_PORT}"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: grocery_web
    command: python manage.py runserver 0.0.0.0:${DJANGO_PORT}
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:${DJANGO_PORT}"
    depends_on:
      - db
      - redis
    healthcheck:
      test:
        ["CMD", "curl", "-f", "http://localhost:${DJANGO_PORT}/health-check"]
      interval: 15s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
