[project]
name = "project_marketly"
version = "0.1.0"
description = "This repository implements a Django application following the principles of Clean Architecture and Domain-Driven Design (DDD). It serves as a practical example of how to structure a robust and maintainable application."
readme = "README.md"
authors = [{ name = "Tyrone Jose" }]
requires-python = ">=3.13"

dependencies = [
  # === Framework ===
  "Django>=4.2,<5.0",
  "djangorestframework>=3.14.0",
  "django-cors-headers>=4.0.0",
  "djangorestframework-simplejwt>=5.5.0",

  # === Utils ===
  "requests>=2.32.4",
  "python-decouple>=3.8",
  "bcrypt>=4.3.0",
  "Pillow>=9.0.0",

  # === Database ===
  "psycopg2-binary>=2.9.0"
]

[project.optional-dependencies]
dev = [
  # === Testing ===
  "pytest>=8.3.4",
  "pytest-django>=4.5.2",
  "pytest-cov>=6.2.1",
  "coverage==7.6.7",
  "django-coverage-plugin==3.1.1",
  "pytest-xdist==3.6.1",
  "factory-boy==3.3.0"
]

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["src"]

[tool.coverage.run]
omit = ["*/migrations/*", "*/tests/*"]
plugins = ["django_coverage_plugin"]
source = ["src"]

[tool.coverage.report]
show_missing = true
skip_covered = true

[tool.ruff]
exclude = [
  ".bzr",
  ".direnv",
  ".eggs",
  ".git",
  ".git-rewrite",
  ".hg",
  ".mypy_cache",
  ".nox",
  ".pants.d",
  ".pytype",
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  "__pypackages__",
  "_build",
  "buck-out",
  "build",
  "dist",
  "node_modules",
  "venv",
  "*/migrations/*.py",
  "*/tests/*.py",
  "staticfiles/*",
]
indent-width = 4
line-length = 120
target-version = "py311"

[tool.black]
line-length = 120
target-version = ["py311"]

[tool.ruff.lint]
ignore = [
  "RUF012",
  "PLR0913",
  "TRY300",
  "TRY301",
  "COM812",
  "ISC001",
]
select = [
  "F",
  "E",
  "W",
  "C90",
  "I",
  "N",
  "UP",
  "YTT",
  "ASYNC",
  "S",
  "BLE",
  "FBT",
  "B",
  "A",
  "COM",
  "C4",
  "DTZ",
  "T10",
  "DJ",
  "EM",
  "EXE",
  "FA",
  'ISC',
  "ICN",
  "G",
  'INP',
  'PIE',
  "T20",
  'PYI',
  'PT',
  "Q",
  "RSE",
  "RET",
  "SLF",
  "SLOT",
  "SIM",
  "TID",
  "TCH",
  "INT",
  "PTH",
  "ERA",
  "PD",
  "PGH",
  "PL",
  "TRY",
  "FLY",
  "PERF",
  "RUF",
]
fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
indent-style = "space"
line-ending = "auto"
quote-style = "double"
skip-magic-trailing-comma = false
