# Generated by Django 4.2.24 on 2025-09-05 16:39

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CartModel",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("user_id", models.UUIDField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cart",
                "verbose_name_plural": "Carts",
                "db_table": "cart",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user_id"], name="cart_user_id_9b8b23_idx"),
                    models.Index(fields=["created_at"], name="cart_created_77417f_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CartItemModel",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("product_id", models.UUIDField()),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10)),
                (
                    "cart_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="items", to="cart.cartmodel"
                    ),
                ),
            ],
            options={
                "verbose_name": "cart item",
                "verbose_name_plural": "cart items",
                "db_table": "cart_item",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(fields=["cart_id"], name="cart_item_cart_id_bee0dd_idx"),
                    models.Index(fields=["product_id"], name="cart_item_product_d993b4_idx"),
                ],
                "unique_together": {("cart_id", "product_id")},
            },
        ),
    ]
