# Generated by Django 4.2.23 on 2025-08-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartitemmodel",
            options={"ordering": ["-id"], "verbose_name": "cart item", "verbose_name_plural": "cart items"},
        ),
        migrations.RemoveIndex(
            model_name="cartitemmodel",
            name="cart_item_cart_id_305f60_idx",
        ),
        migrations.RenameField(
            model_name="cartitemmodel",
            old_name="cart",
            new_name="cart_id",
        ),
        migrations.AlterUniqueTogether(
            name="cartitemmodel",
            unique_together={("cart_id", "product_id")},
        ),
        migrations.AddIndex(
            model_name="cartitemmodel",
            index=models.Index(fields=["cart_id"], name="cart_item_cart_id_bee0dd_idx"),
        ),
        migrations.RemoveField(
            model_name="cartitemmodel",
            name="unit_price",
        ),
    ]
