# Generated by Django 4.2.23 on 2025-08-26 15:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_alter_cartitemmodel_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitemmodel",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
        ),
    ]
