# Generated by Django 4.2.23 on 2025-07-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotionmodel",
            name="discount_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="promotionmodel",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
