# Generated by Django 4.2.23 on 2025-07-24 17:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TransactionModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_id", models.CharField(max_length=64)),
                ("order_id", models.UUIDField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("status", models.CharField(max_length=32)),
                ("payment_method", models.CharField(max_length=32)),
                (
                    "payer_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "payment transaction",
                "verbose_name_plural": "payment transactions",
                "db_table": "payments_transaction",
                "ordering": ("-created_at",),
            },
        ),
    ]
