# Generated by Django 4.2.23 on 2025-08-08 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WishlistModel",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("product_id", models.UUIDField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_id",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "wishlist",
                "verbose_name_plural": "wishlists",
                "db_table": "wishlist",
                "ordering": ["-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="wishlistmodel",
            constraint=models.UniqueConstraint(fields=("user_id", "product_id"), name="unique_user_product"),
        ),
    ]
