# Generated by Django 4.2.24 on 2025-09-05 16:39

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import src.modules.catalog.infrastructure.models.product_model
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BrandModel",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "brand",
                "verbose_name_plural": "brands",
                "db_table": "catalog_brand",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CategoryModel",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
                "db_table": "catalog_category",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField()),
                ("sku", models.CharField(max_length=100, unique=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                ("discount_price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                (
                    "currency",
                    models.CharField(choices=[("USD", "Dollar"), ("CLP", "Chilean Peso")], default="CLP", max_length=3),
                ),
                ("stock", models.PositiveIntegerField(default=0)),
                ("min_stock", models.PositiveIntegerField(default=5)),
                (
                    "warehouse_location",
                    models.CharField(blank=True, help_text="Location where the product is stored", max_length=100),
                ),
                (
                    "image",
                    models.ImageField(upload_to=src.modules.catalog.infrastructure.models.product_model.image_path),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("weight", models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("kg", "Kilogram"),
                            ("g", "Gram"),
                            ("l", "Liter"),
                            ("ml", "Milliliter"),
                            ("unit", "Unit"),
                        ],
                        default="kg",
                        max_length=10,
                    ),
                ),
                ("nutritional_info", models.JSONField(blank=True, null=True)),
                ("ingredients", models.JSONField(blank=True, null=True)),
                ("allergens", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="products", to="catalog.brandmodel"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="products", to="catalog.categorymodel"
                    ),
                ),
            ],
            options={
                "verbose_name": "product",
                "verbose_name_plural": "products",
                "db_table": "catalog_product",
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="categorymodel",
            index=models.Index(fields=["is_active"], name="idx_category_is_active"),
        ),
        migrations.AddIndex(
            model_name="categorymodel",
            index=models.Index(fields=["slug"], name="idx_category_slug"),
        ),
        migrations.AddIndex(
            model_name="brandmodel",
            index=models.Index(fields=["is_active"], name="idx_brand_is_active"),
        ),
        migrations.AddIndex(
            model_name="brandmodel",
            index=models.Index(fields=["slug"], name="idx_brand_slug"),
        ),
        migrations.AddIndex(
            model_name="productmodel",
            index=models.Index(fields=["brand", "is_active"], name="idx_product_brand_active"),
        ),
        migrations.AddIndex(
            model_name="productmodel",
            index=models.Index(fields=["category", "is_active"], name="idx_product_category_active"),
        ),
        migrations.AddIndex(
            model_name="productmodel",
            index=models.Index(fields=["is_featured", "is_active"], name="idx_product_featured_active"),
        ),
        migrations.AddIndex(
            model_name="productmodel",
            index=models.Index(fields=["sku", "is_active"], name="idx_product_sku_active"),
        ),
        migrations.AddIndex(
            model_name="productmodel",
            index=models.Index(fields=["price"], name="idx_product_price"),
        ),
        migrations.AddIndex(
            model_name="productmodel",
            index=models.Index(fields=["slug"], name="idx_product_slug"),
        ),
        migrations.AddConstraint(
            model_name="productmodel",
            constraint=models.CheckConstraint(
                check=models.Q(("discount_price__lt", models.F("price"))), name="discount_lt_price"
            ),
        ),
    ]
