# Generated by Django 4.2.23 on 2025-08-14 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_productmodel_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productmodel",
            old_name="category",
            new_name="category_id",
        ),
    ]
