# Generated by Django 4.2.23 on 2025-08-14 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_rename_category_productmodel_category_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productmodel",
            old_name="category_id",
            new_name="category",
        ),
    ]
