# Generated by Django 4.2.23 on 2025-08-18 18:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_rename_category_id_productmodel_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandModel",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "brand",
                "verbose_name_plural": "brands",
                "db_table": "catalog_brand",
                "ordering": ["name"],
            },
        ),
    ]
