# Generated by Django 4.2.23 on 2025-08-19 16:12

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_brandmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="allergens",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productmodel",
            name="brand",
            field=models.ForeignKey(
                default="afe04928-8c11-4e8f-a723-4a4b0a2de19d",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="catalog.brandmodel",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productmodel",
            name="currency",
            field=models.CharField(choices=[("USD", "Dollar"), ("CLP", "Chilean Peso")], default="CLP", max_length=3),
        ),
        migrations.AddField(
            model_name="productmodel",
            name="ingredients",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productmodel",
            name="nutritional_info",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productmodel",
            name="warehouse_location",
            field=models.CharField(
                blank=True, help_text="Location where the product is stored", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal("0.00"))]
            ),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="unit",
            field=models.CharField(
                choices=[("kg", "Kilogram"), ("g", "Gram"), ("l", "Liter"), ("ml", "Milliliter"), ("unit", "Unit")],
                default="kg",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="productmodel",
            index=models.Index(fields=["brand", "is_active"], name="idx_product_brand_active"),
        ),
        migrations.AddIndex(
            model_name="productmodel",
            index=models.Index(fields=["category", "is_active"], name="idx_product_category_active"),
        ),
        migrations.AddIndex(
            model_name="productmodel",
            index=models.Index(fields=["is_featured", "is_active"], name="idx_product_featured_active"),
        ),
        migrations.AddIndex(
            model_name="productmodel",
            index=models.Index(fields=["sku", "is_active"], name="idx_product_sku_active"),
        ),
        migrations.AddIndex(
            model_name="productmodel",
            index=models.Index(fields=["price"], name="idx_product_price"),
        ),
        migrations.AddConstraint(
            model_name="productmodel",
            constraint=models.CheckConstraint(
                check=models.Q(("discount_price__lt", models.F("price"))), name="discount_lt_price"
            ),
        ),
    ]
