# Generated by Django 4.2.23 on 2025-08-19 20:26

from django.db import migrations, models
import src.modules.catalog.infrastructure.models.product_model


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_productmodel_allergens_productmodel_brand_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodel",
            name="image",
            field=models.ImageField(upload_to=src.modules.catalog.infrastructure.models.product_model.image_path),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="warehouse_location",
            field=models.CharField(blank=True, help_text="Location where the product is stored", max_length=100),
        ),
    ]
