# Generated by Django 4.2.23 on 2025-08-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_alter_productmodel_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandmodel",
            name="slug",
            field=models.CharField(default="temp-slug", max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="categorymodel",
            name="slug",
            field=models.CharField(default="temp-slug", max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productmodel",
            name="slug",
            field=models.CharField(default="temp-slug", max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="brandmodel",
            index=models.Index(fields=["is_active"], name="idx_brand_is_active"),
        ),
        migrations.AddIndex(
            model_name="brandmodel",
            index=models.Index(fields=["slug"], name="idx_brand_slug"),
        ),
        migrations.AddIndex(
            model_name="categorymodel",
            index=models.Index(fields=["is_active"], name="idx_category_is_active"),
        ),
        migrations.AddIndex(
            model_name="categorymodel",
            index=models.Index(fields=["slug"], name="idx_category_slug"),
        ),
        migrations.AddIndex(
            model_name="productmodel",
            index=models.Index(fields=["slug"], name="idx_product_slug"),
        ),
    ]
