# Generated by Django 4.2.24 on 2025-09-05 16:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PromotionModel",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("discount_percent", models.DecimalField(decimal_places=2, max_digits=5)),
                ("is_active", models.BooleanField(default=True)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "promotion",
                "verbose_name_plural": "promotions",
                "db_table": "marketing_promotion",
                "ordering": ["starts_at"],
                "indexes": [models.Index(fields=["is_active"], name="marketing_p_is_acti_98e1a5_idx")],
            },
        ),
        migrations.CreateModel(
            name="CouponModel",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("discount_percent", models.DecimalField(decimal_places=2, max_digits=5)),
                ("is_active", models.BooleanField(default=True)),
                ("max_uses", models.PositiveIntegerField(blank=True, null=True)),
                ("used_count", models.PositiveIntegerField(default=0)),
                ("user_id", models.UUIDField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "coupon",
                "verbose_name_plural": "coupons",
                "db_table": "marketing_coupon",
                "ordering": ["discount_percent"],
                "indexes": [
                    models.Index(fields=["code"], name="marketing_c_code_dee8bf_idx"),
                    models.Index(fields=["is_active"], name="marketing_c_is_acti_946045_idx"),
                ],
            },
        ),
    ]
