# Generated by Django 4.2.23 on 2025-08-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0002_promotionmodel_discount_percent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promotionmodel",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
