from rest_framework import serializers


class ProductInputSerializer(serializers.Serializer):
    name = serializers.CharField(max_length=200)
    description = serializers.CharField()
    sku = serializers.CharField(max_length=100)
    category_id = serializers.UUIDField()
    brand_id = serializers.UUIDField()
    price = serializers.DecimalField(max_digits=10, decimal_places=2)
    discount_price = serializers.DecimalField(max_digits=10, decimal_places=2, required=False, allow_null=True)
    currency = serializers.CharField(max_length=3, required=False, allow_null=True)
    stock = serializers.IntegerField()
    min_stock = serializers.IntegerField()
    warehouse_location = serializers.CharField(max_length=100, required=False, allow_null=True)
    image = serializers.ImageField()
    is_active = serializers.BooleanField()
    is_featured = serializers.BooleanField()
    weight = serializers.DecimalField(max_digits=8, decimal_places=3, required=False, allow_null=True)
    unit = serializers.CharField(max_length=10)
    nutritional_info = serializers.JSONField(required=False, allow_null=True)
    ingredients = serializers.JSONField(required=False, allow_null=True)
    allergens = serializers.JSONField(required=False, allow_null=True)


class ProductOutputSerializer(serializers.Serializer):
    id = serializers.UUIDField(read_only=True)
    name = serializers.CharField(read_only=True)
    slug = serializers.CharField(read_only=True)
    description = serializers.CharField(read_only=True)
    sku = serializers.CharField(read_only=True)
    category_id = serializers.UUIDField(read_only=True)
    brand_id = serializers.UUIDField(read_only=True)
    price = serializers.DecimalField(max_digits=10, decimal_places=2, read_only=True)
    discount_price = serializers.DecimalField(max_digits=10, decimal_places=2, read_only=True)
    currency = serializers.CharField(read_only=True)
    stock = serializers.IntegerField(read_only=True)
    min_stock = serializers.IntegerField(read_only=True)
    warehouse_location = serializers.CharField(read_only=True)
    image_url = serializers.URLField(read_only=True)
    is_active = serializers.BooleanField()
    is_featured = serializers.BooleanField()
    weight = serializers.DecimalField(max_digits=8, decimal_places=3, read_only=True)
    unit = serializers.CharField(read_only=True)
    nutritional_info = serializers.JSONField(read_only=True)
    ingredients = serializers.JSONField(read_only=True)
    allergens = serializers.JSONField(read_only=True)
    created_at = serializers.DateTimeField(read_only=True)
    updated_at = serializers.DateTimeField(read_only=True)
