from uuid import uuid4

import pytest

from src.modules.users.domain.entities.user import User
from src.modules.users.domain.value_objects.email import Email
from src.modules.users.domain.value_objects.username import Username
from src.modules.users.infrastructure.models.user_model import UserModel
from src.modules.users.infrastructure.repositories.user_repository import UserRepository


@pytest.mark.django_db()
class TestUserRepository:
    def test_user_repository_create_and_get_by_id(self) -> None:
        # Given: a user entity to be created
        repo = UserRepository()
        user = User(
            id=uuid4(),
            email=Email("test@example.com"),
            username=Username("testuser"),
            password="hashedpwd",
            first_name="Test",
            last_name="User",
            is_active=True,
            is_staff=False,
            is_superuser=False,
        )

        # When: creating the user via the repository
        saved = repo.create(user)

        # Then: returned user matches input (except id generated by DB)
        assert saved.email == user.email
        assert saved.username == user.username
        assert saved.is_active is True

        # When: get user by ID
        fetched = repo.get_by_id(saved.id)

        # Then: retrieved user matches created user
        assert fetched is not None
        assert fetched.id == saved.id
        assert fetched.email == user.email.value

    def test_user_repository_get_by_id_returns_none_when_not_found(self) -> None:
        # Given: a random user ID that does not exist
        repo = UserRepository()

        # When: fetching user by that ID
        result = repo.get_by_id(uuid4())

        # Then: result should be None
        assert result is None

    def test_user_repository_get_by_email_or_username_success(self) -> None:
        # Given: a user saved in the DB
        UserModel.objects.create(
            email="email@test.com",
            username="user123",
            password="pwd",
            first_name="First",
            last_name="Last",
            is_active=True,
            is_staff=False,
            is_superuser=False,
        )
        repo = UserRepository()

        # When: searching by email or username
        user = repo.get_by_email_or_username("email@test.com", "otheruser")

        # Then: user is found by email
        assert user is not None
        assert user.email == "email@test.com"

        # When: searching by username
        user = repo.get_by_email_or_username("otheremail@test.com", "user123")

        # Then: user is found by username
        assert user is not None
        assert user.username == "user123"

    def test_user_repository_get_by_email_or_username_returns_none_if_not_found(self) -> None:
        # Given: no user with this email or username
        repo = UserRepository()

        # When: searching by non-existing email and username
        user = repo.get_by_email_or_username("noemail@test.com", "nouser")

        # Then: no user is found
        assert user is None

    def test_user_repository_list_all_returns_only_active_users(self) -> None:
        # Given: active and inactive users in DB
        UserModel.objects.create(
            email="active1@test.com",
            username="active1",
            password="pwd",
            first_name="First",
            last_name="Last",
            is_active=True,
            is_staff=False,
            is_superuser=False,
        )
        UserModel.objects.create(
            email="inactive@test.com",
            username="inactive",
            password="pwd",
            first_name="First1",
            last_name="Last2",
            is_active=False,
            is_staff=False,
            is_superuser=False,
        )
        repo = UserRepository()

        # When: listing all active users
        users = repo.list_all()

        # Then: all returned users are active
        assert all(user.is_active for user in users)
        assert any(user.email == "active1@test.com" for user in users)
        assert all(user.email != "inactive@test.com" for user in users)

    def test_user_repository_update_existing_user(self) -> None:
        # Given: an existing user in DB
        user_model = UserModel.objects.create(
            email="old@test.com",
            username="olduser",
            password="oldpwd",
            first_name="Old",
            last_name="User",
            is_active=True,
            is_staff=False,
            is_superuser=False,
        )
        repo = UserRepository()

        # And: new user data to update
        new_user_data = User(
            id=user_model.id,
            email=Email("new@test.com"),
            username=Username("newuser"),
            password="newpwd",
            first_name="New",
            last_name="User",
            is_active=True,
            is_staff=True,
            is_superuser=True,
        )

        # When: updating the user
        updated = repo.update(user_model.id, new_user_data)

        # Then: updated user reflects changes
        assert updated is not None
        assert updated.email == "new@test.com"
        assert updated.username == "newuser"
        assert updated.is_staff is True
        assert updated.is_superuser is True

    @pytest.mark.django_db()
    def test_user_repository_update_returns_none_when_user_not_found(self) -> None:
        # Given: a user entity to update and a non-existing ID
        repo = UserRepository()
        dummy_user = User(
            id=uuid4(),
            email=Email("no@user.com"),
            username=Username("nouser"),
            password="pwd",
            first_name="No",
            last_name="User",
            is_active=True,
            is_staff=False,
            is_superuser=False,
        )

        # When: attempting to update non-existing user
        updated = repo.update(uuid4(), dummy_user)

        # Then: update returns None
        assert updated is None

    @pytest.mark.django_db()
    def test_user_repository_delete_sets_is_active_false(self) -> None:
        # Given: an active user in DB
        user_model = UserModel.objects.create(
            email="delete@test.com",
            username="todelete",
            password="pwd",
            is_active=True,
            is_staff=False,
            is_superuser=False,
        )
        repo = UserRepository()

        # When: deleting the user (soft delete)
        repo.delete(user_model.id)

        # Then: user is marked as inactive
        refreshed = UserModel.objects.get(pk=user_model.id)
        assert refreshed.is_active is False

    @pytest.mark.django_db()
    def test_user_repository_delete_no_error_if_user_not_found(self) -> None:
        # Given: a random user ID that does not exist
        repo = UserRepository()

        # When & Then: delete does not raise error
        repo.delete(uuid4())
